sudo: false
language: node_js
node_js:
  - 5
env:
  - SITE_URL=https://demoneaux.github.io/lodash-docs-experiment
git:
  depth: 10
script:
  - npm run build
after_success:
  - $(npm bin)/update-branch --commands "true"
                             --commit-message "Update content [ci skip]"
                             --directory "build"
                             --distribution-branch "gh-pages"
                             --source-branch "master"
